### ISSUE TITLE
error: specified package `probe-rs-rtt v0.3.0` has no binaries

### ISSUE THREAD

**Issue by brainstorm** [probe-rs/probe-rs-rtt#15]
**Describe the bug**
```
$ cargo install probe-rs-rtt
    Updating crates.io index
error: specified package `probe-rs-rtt v0.3.0` has no binaries
```

**Expected behavior**

`rtthost` binary (and other RTT tooling?) installed like any other `cargo install <pkg>`, without the need to resort to `./target/release/rtthost`.

**Desktop (please complete the following information):**
 - macOS Catalina

**Comment by Yatekii** [comment]
This is intended behavior. `probe-rs-rtt` is a library. If you wanted `rtthost`, you'd need to do `cargo install rtthost` ofc. That binary crate is not published tho. What's used normally is `cargo-embed`.

**Comment by mvirkkunen** [comment]
Hmm, would it such a bad idea to publish "rtthost"? Either as a binary in probe-rs-rtt or separately. Sometimes it's handy to just be able to look at logging output without anything else.

**Comment by Yatekii** [comment]
I mean I personally don't see the use, but I see no issues with publishing it :)
