### ISSUE TITLE
Transfer speed might be faster using read_32 instead of read_8

### ISSUE THREAD

**Issue by davidlattimore** [probe-rs/probe-rs-rtt#27]
I'm looking at using probe-rs-rtt to transfer small images off an stm32g031 for debugging / development purposes. The images are around 78KiB. If I send them over an RTT channel, it takes about 11 seconds. If however I change probe-rs-rtt to use `read_32` instead of `read_8` to read the data then the transfer time drops to about 2.7 seconds.

Since `read_32` requires that the address be 32 bit aligned, this required reading all the 32 bit words that overlap with the desired range of bytes into a Vec<u32> then copying the data into the output byte slice, converting to bytes using the target device's endianness.

I was wondering what you would think of such an optimization?

**Comment by Yatekii** [comment]
I think this would be a good optimization!

Your numbers do not add up to me tho. it should not take 2.7s to transfer only 78KiB. Maybe that's really because the suboptimal reads/writes and the block size of RTT. What is your debug probe and line speed and is this raw transfer or also some other operations?

**Comment by mvirkkunen** [comment]
I seem to remember making this sort of optimization on the `probe-rs` end at some point instead of putting it in `probe-rs-rtt`. Let me check why it's not being used.

**Comment by davidlattimore** [comment]
Since the chip I'm using only has 8KiB of RAM, I was receiving the data over SPI then sending it out to the channel. However, I've now done a test that removes that part and just writes a fixed sequence of bytes repeatedly to the channel then measured the speed on the host side. With the channel using `read_8`, I get a speed of 6.7KB/s. With `read_32`, I get a speed of 45KB/s.

My probe is an ST-Link V2. I put a scope on the clock line and it seems to be running at around 1.8Mhz.

Doing the optimization at the probe-rs level sounds good to me, if that's considered an appropriate place to do it. I just sent a PR to do that.
